name: Build & Publish Docker

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Przygotuj emulację ARM
        uses: docker/setup-qemu-action@v3

      - name: Przygotuj Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Zaloguj do Docker Hub (cache)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Zaloguj do GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Ustal skrócony SHA
        id: vars
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Buduj i wypychaj obraz
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=nadiiamartyniuk/cache
          cache-to:   type=registry,ref=nadiiamartyniuk/cache,mode=max
          push: true
          tags: |
            ghcr.io/nadiiamartyniuk/${{ github.repository }}:sha-${{ steps.vars.outputs.short_sha }}
            ghcr.io/nadiiamartyniuk/${{ github.repository }}:latest

      - name: Skanuj obraz Trivy
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          scan-type: image
          image-ref: ghcr.io/nadiiamartyniuk/${{ github.repository }}:sha-${{ steps.vars.outputs.short_sha }}
          severity: CRITICAL,HIGH
          exit-code: 1
